version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kanban-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
      POSTGRES_DB: kanban_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban_user -d kanban_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
